export const INIT_SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS tenants (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(100) NOT NULL UNIQUE,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS companies (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  name VARCHAR(255) NOT NULL,
  legal_name VARCHAR(255),
  commercial_registration VARCHAR(255),
  tax_number VARCHAR(100),
  currency VARCHAR(10) DEFAULT 'SAR' NOT NULL,
  settings JSONB,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS branches (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  company_id VARCHAR(255) NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(100) NOT NULL,
  address TEXT,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  company_id VARCHAR(255) REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id VARCHAR(255) REFERENCES branches(id) ON DELETE RESTRICT,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  role VARCHAR(100) NOT NULL,
  password_hash VARCHAR(255),
  status VARCHAR(50) DEFAULT 'ACTIVE' NOT NULL,
  failed_login_attempts INTEGER DEFAULT 0 NOT NULL,
  last_login_at TIMESTAMP WITH TIME ZONE,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  CONSTRAINT users_tenant_username_unique UNIQUE(tenant_id, username),
  CONSTRAINT users_tenant_email_unique UNIQUE(tenant_id, email)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  token_hash VARCHAR(255) NOT NULL,
  is_revoked BOOLEAN DEFAULT false NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  company_id VARCHAR(255) NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id VARCHAR(255) REFERENCES branches(id) ON DELETE RESTRICT,
  timestamp VARCHAR(255) NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  action VARCHAR(255) NOT NULL,
  details TEXT NOT NULL,
  old_value TEXT,
  new_value TEXT,
  reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS roles (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  company_id VARCHAR(255) REFERENCES companies(id) ON DELETE CASCADE,
  code VARCHAR(100) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  is_system_role BOOLEAN DEFAULT false NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS permissions (
  id VARCHAR(255) PRIMARY KEY,
  code VARCHAR(100) NOT NULL UNIQUE,
  module VARCHAR(100) NOT NULL,
  description TEXT
);

CREATE TABLE IF NOT EXISTS role_permissions (
  role_id VARCHAR(255) NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  permission_id VARCHAR(255) NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  role_id VARCHAR(255) NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS user_company_access (
  user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  company_id VARCHAR(255) NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  branch_id VARCHAR(255) REFERENCES branches(id) ON DELETE CASCADE,
  granted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  PRIMARY KEY (user_id, tenant_id, company_id)
);

CREATE TABLE IF NOT EXISTS accounts (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  company_id VARCHAR(255) NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  code VARCHAR(100) NOT NULL,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(50) NOT NULL,
  parent_account_id VARCHAR(255),
  currency VARCHAR(10) DEFAULT 'SAR' NOT NULL,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS fiscal_years (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  company_id VARCHAR(255) NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  year INTEGER NOT NULL,
  start_date VARCHAR(50) NOT NULL,
  end_date VARCHAR(50) NOT NULL,
  is_closed BOOLEAN DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS fiscal_periods (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  company_id VARCHAR(255) NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  fiscal_year_id VARCHAR(255) NOT NULL REFERENCES fiscal_years(id) ON DELETE RESTRICT,
  period_number INTEGER NOT NULL,
  name VARCHAR(100) NOT NULL,
  start_date VARCHAR(50) NOT NULL,
  end_date VARCHAR(50) NOT NULL,
  status VARCHAR(50) DEFAULT 'OPEN' NOT NULL
);

CREATE TABLE IF NOT EXISTS journal_entries (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  company_id VARCHAR(255) NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id VARCHAR(255) REFERENCES branches(id) ON DELETE RESTRICT,
  entry_number VARCHAR(100) NOT NULL,
  date VARCHAR(50) NOT NULL,
  reference VARCHAR(255),
  notes TEXT,
  status VARCHAR(50) DEFAULT 'DRAFT' NOT NULL,
  posted_at TIMESTAMP WITH TIME ZONE,
  posted_by VARCHAR(255),
  reversed_entry_id VARCHAR(255),
  fiscal_period_id VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS journal_entry_items (
  id VARCHAR(255) PRIMARY KEY,
  journal_entry_id VARCHAR(255) NOT NULL REFERENCES journal_entries(id) ON DELETE CASCADE,
  account_id VARCHAR(255) NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,
  debit NUMERIC(15,2) DEFAULT 0 NOT NULL,
  credit NUMERIC(15,2) DEFAULT 0 NOT NULL,
  description TEXT
);

CREATE TABLE IF NOT EXISTS customers (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  company_id VARCHAR(255) NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(100) NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(100),
  tax_number VARCHAR(100),
  address TEXT,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS suppliers (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  company_id VARCHAR(255) NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(100) NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(100),
  tax_number VARCHAR(100),
  address TEXT,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  company_id VARCHAR(255) NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  code VARCHAR(100) NOT NULL,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  uom VARCHAR(50) NOT NULL,
  cost_price NUMERIC(15,2) DEFAULT 0 NOT NULL,
  selling_price NUMERIC(15,2) DEFAULT 0 NOT NULL,
  reorder_level INTEGER DEFAULT 0 NOT NULL,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS stock_batches (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  company_id VARCHAR(255) NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  item_id VARCHAR(255) NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  batch_number VARCHAR(100) NOT NULL,
  quantity NUMERIC(15,2) DEFAULT 0 NOT NULL,
  cost_price NUMERIC(15,2) DEFAULT 0 NOT NULL,
  expiry_date VARCHAR(50),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS cost_layers (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  company_id VARCHAR(255) NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  item_id VARCHAR(255) NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  quantity NUMERIC(15,2) DEFAULT 0 NOT NULL,
  remaining_quantity NUMERIC(15,2) DEFAULT 0 NOT NULL,
  unit_cost NUMERIC(15,2) DEFAULT 0 NOT NULL,
  received_date VARCHAR(50) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS stock_movements (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  company_id VARCHAR(255) NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id VARCHAR(255) REFERENCES branches(id) ON DELETE RESTRICT,
  item_id VARCHAR(255) NOT NULL REFERENCES items(id) ON DELETE RESTRICT,
  type VARCHAR(50) NOT NULL,
  quantity NUMERIC(15,2) DEFAULT 0 NOT NULL,
  unit_cost NUMERIC(15,2) DEFAULT 0 NOT NULL,
  total_cost NUMERIC(15,2) DEFAULT 0 NOT NULL,
  reference VARCHAR(255),
  movement_date VARCHAR(50) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS sales_invoices (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  company_id VARCHAR(255) NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id VARCHAR(255) REFERENCES branches(id) ON DELETE RESTRICT,
  invoice_number VARCHAR(100) NOT NULL,
  customer_id VARCHAR(255) REFERENCES customers(id) ON DELETE RESTRICT,
  date VARCHAR(50) NOT NULL,
  due_date VARCHAR(50),
  status VARCHAR(50) DEFAULT 'DRAFT' NOT NULL,
  subtotal NUMERIC(15,2) DEFAULT 0 NOT NULL,
  tax_amount NUMERIC(15,2) DEFAULT 0 NOT NULL,
  discount_amount NUMERIC(15,2) DEFAULT 0 NOT NULL,
  total_amount NUMERIC(15,2) DEFAULT 0 NOT NULL,
  journal_entry_id VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS sales_invoice_items (
  id VARCHAR(255) PRIMARY KEY,
  sales_invoice_id VARCHAR(255) NOT NULL REFERENCES sales_invoices(id) ON DELETE CASCADE,
  item_id VARCHAR(255) NOT NULL REFERENCES items(id) ON DELETE RESTRICT,
  quantity NUMERIC(15,2) DEFAULT 0 NOT NULL,
  unit_price NUMERIC(15,2) DEFAULT 0 NOT NULL,
  tax_rate NUMERIC(5,2) DEFAULT 0 NOT NULL,
  tax_amount NUMERIC(15,2) DEFAULT 0 NOT NULL,
  total_price NUMERIC(15,2) DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS purchase_orders (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  company_id VARCHAR(255) NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id VARCHAR(255) REFERENCES branches(id) ON DELETE RESTRICT,
  order_number VARCHAR(100) NOT NULL,
  supplier_id VARCHAR(255) REFERENCES suppliers(id) ON DELETE RESTRICT,
  date VARCHAR(50) NOT NULL,
  expected_delivery_date VARCHAR(50),
  status VARCHAR(50) DEFAULT 'DRAFT' NOT NULL,
  subtotal NUMERIC(15,2) DEFAULT 0 NOT NULL,
  tax_amount NUMERIC(15,2) DEFAULT 0 NOT NULL,
  total_amount NUMERIC(15,2) DEFAULT 0 NOT NULL,
  journal_entry_id VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS purchase_order_items (
  id VARCHAR(255) PRIMARY KEY,
  purchase_order_id VARCHAR(255) NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
  item_id VARCHAR(255) NOT NULL REFERENCES items(id) ON DELETE RESTRICT,
  quantity NUMERIC(15,2) DEFAULT 0 NOT NULL,
  unit_cost NUMERIC(15,2) DEFAULT 0 NOT NULL,
  total_cost NUMERIC(15,2) DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS document_sequences (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  company_id VARCHAR(255) NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  document_type VARCHAR(100) NOT NULL,
  prefix VARCHAR(50) NOT NULL,
  current_value INTEGER DEFAULT 0 NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS warehouses (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  company_id VARCHAR(255) NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id VARCHAR(255) REFERENCES branches(id) ON DELETE RESTRICT,
  code VARCHAR(100) NOT NULL,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE IF NOT EXISTS sync_queue (
  id VARCHAR(255) PRIMARY KEY,
  tenant_id VARCHAR(255) NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  company_id VARCHAR(255) NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id VARCHAR(255) REFERENCES branches(id) ON DELETE RESTRICT,
  idempotency_key VARCHAR(255) NOT NULL,
  entity_type VARCHAR(100) NOT NULL,
  operation VARCHAR(50) NOT NULL,
  payload TEXT NOT NULL,
  status VARCHAR(50) DEFAULT 'PENDING' NOT NULL,
  retry_count INTEGER DEFAULT 0 NOT NULL,
  last_error TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  processed_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT sync_queue_idempotency_unique UNIQUE(tenant_id, idempotency_key)
);
`;
